### PR TITLE
Nmc refactoring dev

### PR DESCRIPTION
**Pull request by MJGaughran**
This implements all of the module creator changes that Nick suggested, plus a few of my own.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
Phew that's a lot of stuff :smile: 
Comment @nickbattam?

**Comment by nickbattam** [comment]
Some unit test names are very long. This makes it hard to check all the cases are covered.
It would be clearer to create (for e.g. GetModuleCreator tests) separate test classes for Python, Ioc, BL, Support, Tools, ....
Having done that you'd be able to be able to drop the 'given_area_is_ioc_and_tech_area_is_BL' prefix and just include information about the specific test in the name.

Think about the unit tests as a document defining the behaviour. If you just wrote that you'd have:
- beamlines -- does A, B, C
- IOCs -- does A, C and D
- Support -- does A, B, D, E and F
- tools ... 

You will probably end up with 'duplicate' tests in each class but that doesn't matter as you're showing that the behaviour works in that case.

**Comment by MJGaughran** [comment]
This is the final version. There are a couple more minor, but time-consuming changes suggested, but I'll only do them if I have time after systems testing.

**Comment by MJGaughran** [comment]
This ought to be the actual final version.

**Comment by nickbattam** [comment]
@ulrikpedersen Looks good to me

**Pull request merged**
