### PR TITLE
Add configure/VERSION file when releasing

### PR DESCRIPTION
**Pull request by mfurseman**
These changes have been made to dls_release 2-5.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
Thanks Matt :+1: 

I've noticed that this PR fails a unittest. Although I can't see why your commit could cause this...

Perhaps @GDYendell or @MJGaughran could take a quick look to see if they recognise the failure?

**Comment by mfurseman** [comment]
All the tests still pass on my machine. I had an issue similar to this when Travis changed the default version of Python a few months ago.

**Comment by GDYendell** [comment]
There was a minor change to GitPython that made the mock error raising incorrect. Should we have a fixed GitPython version? It's currently >=0.3.2; (the new version is 2.1.0).

**Comment by ulrikpedersen** [comment]
Thanks Gary. I think we'll leave it like this for now. We need to update our internal (/dls_sw/prod/tools/) installation of GitPython first. That is currently sat at 0.3.2.RC1 - so an update is well overdue...

**Pull request merged**
