### PR TITLE
Add os.getlogin patch for module_creator_test

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by GDYendell** [comment]
@ulrikpedersen These tests failed in my recent branch with OSError: [Errno 25] Inappropriate ioctl for device in os.getlogin() . I reran the successful merge on master and it failed there as well. I'm not sure why this is suddenly happening, but it seems like a good idea to mock out os.getlogin, regardless.

**Comment by ulrikpedersen** [comment]
That is a bit strange... The unittest presumably do not care much about the content of the username, right? So you instead of mocking out the test you could probably just catch the exception (OSError) in your main code (not test code), print an exception log message and fill in the username by other means.

There are alternatives to os.getlogin(). From the python manual:

> os.getlogin()
Return the name of the user logged in on the controlling terminal of the process. For most purposes, it is more useful to use the environment variable LOGNAME to find out who the user is, or pwd.getpwuid(os.getuid())[0] to get the login name of the process’s real user id.

Try to see if any of these methods works better.

**Comment by GDYendell** [comment]
Should we be using LOGNAME rather than USER?

**Comment by GDYendell** [comment]
Closing this and making the fix in #43.

**Pull request closed without merging**
