### PR TITLE
List branches git dev

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
@GDYendell  - this PR has some conflicts that need to be resolved before we can merge... It appears to be in vcs_git.py and vcs_git_test.py. Please merge new-git-scripts into this branch on your local clone and resolve the conflicts (but do a fetch first as I have just merged your other pull request).

It also looks like it has some of my commits at the top which I'm pretty sure I did not add to this branch. I'm a bit confused about that...

**Comment by GDYendell** [comment]
OK, this has been merged and is ready to check over, but the Landscape check failed.

**Comment by willrogers** [comment]
It looks to me like Landscape is just being a bit flaky at the moment.

**Comment by ulrikpedersen** [comment]
Landscape is a one-man-band apparently - and he's in hospital... :crying_cat_face:  https://twitter.com/landscapeio

**Pull request merged**
