### PR TITLE
Update required version of GitPython.

### PR DESCRIPTION
**Pull request by willrogers**
It was pinned to 0.3.2.RC1. I have pinned it to 2.1.5.

@ulrikpedersen @GDYendell

### CODE REVIEW

**Comment by GDYendell** [comment]
Does 'packed refs' problem go away with this change?

**Comment by willrogers** [comment]
I found it a bit hard to reproduce, so I'm not sure.

**Comment by mfurseman** [comment]
Will this be an issue when releasing for RHEL6 and RHEL7. I am about to make a RHEL6 release without this change. However once merged will we need to keep a legacy RHEL6 branch to depend on older libraries?

**Comment by willrogers** [comment]
We can do that and I don't think it's a problem. Further releases on RHEL6 can be point releases of whatever version you release.

To keep things simple, perhaps all RHEL6 versions should be behind all RHEL7 versions.

**Comment by willrogers** [comment]
Better...?

**Comment by mfurseman** [comment]
It seems the packed-refs problem with Git 2.15 was solved and the patched version released (yesterday) as GitPython 2.1.8. https://github.com/gitpython-developers/GitPython/issues/687

**Pull request merged**
