### PR TITLE
Remove default commit message from stage_all_files_and_commit

### PR DESCRIPTION
**Pull request by GDYendell**
Update usage to explicitly pass 'Inital commit'
Update tests

### CODE REVIEW

**Comment by GDYendell** [comment]
The unittests pass. I couldn't get the system tests to run.

**Comment by GDYendell** [comment]
Fixes CGP-19, which has been on my backlog for a while now.

**Comment by willrogers** [comment]
Hold on, why couldn't you get the system tests to run?

**Comment by GDYendell** [comment]
I get this:

`Traceback (most recent call last):
  File "push_required_repos.py", line 6, in <module>
    from dls_ade import Server
ImportError: No module named dls_ade`

I can fix that by adding the full path to the dls_ade egg to the PYTHONPATH, but the I get

`Traceback (most recent call last):
  File "push_required_repos.py", line 6, in <module>
    from dls_ade import Server
  File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/__init__.py", line 1, in <module>
    from gitoliteserver import GitoliteServer as Server
  File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/gitoliteserver.py", line 8, in <module>
    from dls_ade.gitserver import GitServer
  File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/gitserver.py", line 5, in <module>
    from dls_ade.vcs_git import Git, git
  File "/scratch/work/common/python/RHEL7-x86_64/dls_ade/prefix/lib/python2.7/site-packages/dls_ade-0.0-py2.7.egg/dls_ade/vcs_git.py", line 3, in <module>
    import git
ImportError: No module named git`

I discussed this with @skyfrench at one point. She managed to get it to work without the require("git") in vcs_git and removed it, but I can't remember what the fix was.

**Comment by willrogers** [comment]
Well, let's get the instructions adequate...

**Comment by GDYendell** [comment]
Agreed. I have put in an issue.

**Comment by skyfrench** [comment]
Will need some investigation to work out what is causing the instructions not to work for Gary. The instructions work for me when followed on both my old and new linux workstations (both RHEL6), so it's not repeatable everywhere.

**Comment by skyfrench** [comment]
I've run the system tests - just one test fix needed (and the repo_test_num.txt file wasn't up to date for the start_new_module tests).

**Comment by skyfrench** [comment]
Could you try with the updated setup_testing_environment.sh script I've just committed? I logged into your workstation and reproduced the errors you were getting. I then got it to run after modifying the bash setup script to setup the path more explicitly. The new script still works on my machine too. I don't however understand why it needs the egg files explicitly in the path ...

**Comment by willrogers** [comment]
@GDYendell, you should be able to rebase on master now and then we can merge this.

**Comment by GDYendell** [comment]
Only (13/29 of) the tests on start-new-module fail now.

**Comment by willrogers** [comment]
All of the system tests seem to be passing on the `python3_wsystests` branch now. However, it is by no means obvious why the ones on this branch are failing still.

I talked briefly to @MJGaughran about the system tests. At the moment they are a bit of a burden. Also, at some point we will be moving to a different server and some of them will break as a result. I guess either:

* we ditch them altogether
* someone (possibly Gary and Martin as the original authors (?)) take a bit of time to get rid of the more brittle ones and understand what features would be useful and how to make the tests more robust

**Comment by willrogers** [comment]
But let's not hold up everything because of that.

**Pull request merged**
