### PR TITLE
Remove obsolete warning about Subversion.

### PR DESCRIPTION
**Pull request by willrogers**
@GDYendell am I wrong?

### CODE REVIEW

**Comment by GDYendell** [comment]
Nope, this is correct. None of the scripts use pysvn, although it is still lingering in an unused file.

Feel free to merge.

**Comment by willrogers** [comment]
Should we remove the unused file then? It's always in Git history.

**Comment by GDYendell** [comment]
I guess we can; dls_environment.pysvn is the script. It looks like it is imported by two of the py_scripts, all of which will be removed eventually, as will the entire dls_environment directory.

**Comment by willrogers** [comment]
'Eventually'? Should we remove it now then? There's probably some context I'm missing here.

@ulrikpedersen ?

**Comment by GDYendell** [comment]
Eventually because some remaining scripts may still be converted to git and we want to keep the commit history if we do so.

I am fairly sure dls_environment is completely redundant now, though, so that can probably be removed.

**Comment by ulrikpedersen** [comment]
> Eventually because some remaining scripts may still be converted to git and we want to keep the commit history if we do so.

What scripts might that be?

> I am fairly sure dls_environment is completely redundant now, though, so that can probably be removed.

Yes, I'd like to remove it if it really is no longer used. As Will mention: there is always the git history...

**Comment by GDYendell** [comment]
> What scripts might that be?

The vendor and publish scripts were still undecided last time we discussed this, I think.

**Comment by ulrikpedersen** [comment]
> The vendor and publish scripts were still undecided last time we discussed this, I think.

Ah, OK. Both of those would require significant rewrite to support git instead of subversion and github instead of our own website... We do not need to carefully retain a contiguous history for these scripts.

Let's remove dls_environment

**Comment by willrogers** [comment]
OK, I've removed all of both. The tests still pass locally. Ulrik should check before merging.

**Comment by ulrikpedersen** [comment]
I wasn't sure if git_functions.py and options.py from dls_environment wasn't used anymore... However, the tests pass so I guess they were indeed obsolete.

**Pull request merged**
