### PR TITLE
Use Matlab area in Git

### PR DESCRIPTION
**Pull request by mfurseman**
This addresses https://github.com/dls-controls/dls_ade/issues/50. I think I caught all the places in the code where the is specific handling of the module area, so Matlab and Git should work for all the dls scripts now.

### CODE REVIEW

**Comment by mfurseman** [comment]
I'd like to get this into dls_ade (and then get it released...) so that I can begin using it for Matlab work.
Greatly appreciated if someone could review @GDYendell @arvinderpalaha @MJGaughran

**Comment by GDYendell** [comment]
This looks good. I will defer review of the module creator parts to @MJGaughran . Are you able to test this with a local checkout to see if you can use Matlab as expected?

**Comment by mfurseman** [comment]
I have run all the scripts with the exception of dls-start-new-module, and everything worked as I would have expected.

**Comment by MJGaughran** [comment]
Everything appears to be fine.

**Comment by mfurseman** [comment]
@ulrikpedersen Are you happy for this to be merged?

**Comment by ulrikpedersen** [comment]
> I'd like to get this into dls_ade (and then get it released...) so that I can begin using it for Matlab work.

about getting it released... ASFAIK we have not yet made a release. We should make a release for RHEL6 - but will not put it in peoples environment (configure-tool) as it would override all of the existing dls-* scripts. For RHEL7 we plan to do a release that **will** be loaded into the default environment.

**Pull request merged**
