### PR TITLE
Implement test framework using virtualenv

### LINKED ISSUE #76: System Test Instructions
Improve system test instructions and setup scripts so that they just work.

### PR DESCRIPTION
**Pull request by GDYendell**
Fixes #76

### CODE REVIEW

**Comment by GDYendell** [comment]
I think this works nicely for RHEL6 and 7, but not Python 3. The system test setup script now doesn't take any arguments; its all managed through the virtual environment.

**Comment by willrogers** [comment]
Thanks Gary. I think this installation method works well.

I still get some failures on RHEL7, along the lines of the following:

```
======================================================================
FAIL: list_releases_for_a_module_in_prod_python
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hgs15624/code/python/dls_ade/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/hgs15624/code/python/dls_ade/system_testing/system_testing.py", line 342, in __call__
    self.run_tests()
  File "/home/hgs15624/code/python/dls_ade/system_testing/system_testing.py", line 423, in run_tests
    self.check_std_out_and_exceptions()
  File "/home/hgs15624/code/python/dls_ade/system_testing/system_testing.py", line 447, in check_std_out_and_exceptions
    self.compare_std_out_to_string()
  File "/home/hgs15624/code/python/dls_ade/system_testing/system_testing.py", line 498, in compare_std_out_to_string
    for elem in expected_string_components))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
root: DEBUG: The test's local variables are:
root: DEBUG: _std_out: 
root: DEBUG: _std_out_ends_with_string: None
root: DEBUG: _settings_list: ['default_server_repo_path', 'exception_type', 'exception_string', 'std_out_compare_string', 'std_out_starts_with_string', 'std_out_ends_with_string', 'arguments', 'input', 'attributes_dict', 'server_repo_path', 'local_repo_path', 'repo_comp_method', 'local_comp_path_one', 'local_comp_path_two', 'branch_name']
root: DEBUG: _exception_string: 
root: DEBUG: _attributes_dict: {}
root: DEBUG: _exception_type: 
root: DEBUG: _input: None
root: DEBUG: _repo_comp_method: 
root: DEBUG: _server_repo_clone_path: 
root: DEBUG: _local_repo_path: 
root: DEBUG: _script: dls-list-releases.py
root: DEBUG: _server_repo_path: 
root: DEBUG: description: list_releases_for_a_module_in_prod_python
root: DEBUG: _default_server_repo_path: 
root: DEBUG: _std_out_starts_with_string: None
root: DEBUG: _branch_name: 
root: DEBUG: _std_err: 
root: DEBUG: _return_code: None
root: DEBUG: _std_out_compare_string: Previous releases for dls_pilatus in prod: ['1-0', '1-1', '1-2', '1-3']
root: DEBUG: server: <dls_ade.gitoliteserver.GitoliteServer object at 0x7f32c8bb2450>
root: DEBUG: _arguments: -p dls_pilatus
root: DEBUG: _local_comp_path_one: 
root: DEBUG: _local_comp_path_two: 
root: DEBUG: End of local variables.
root: DEBUG: About to call script with: dls-list-releases.py -p dls_pilatus
root: DEBUG: standard out:
dls_pilatus: No releases made for R3.14.12.7

root: DEBUG: standard error:

root: DEBUG: return code: 0
root: DEBUG: Performing tests.
root: DEBUG: Comparing the standard output to comparison string.
--------------------- >> end captured logging << ---------------------
```

A quick look suggests it's something along the lines of the changed environment (`R3.14.12.3` -> `R3.14.12.7`), but I'm not sure.

**Comment by GDYendell** [comment]
Yeah I get that too. I'm not sure what to do about that as it relies on things being in prod under a specific EPICS version. It will be a pain to make it work for both at the same time. We could spoof the EPICS version in the environment temporarily.

**Comment by GDYendell** [comment]
@willrogers and @skyfrench this latest commit fixes the list-releases in prod tests by setting DLS_EPICS_VERSION in the setup script and by explicitly using -r 6 on the tests that were failing.

There are still start-new-module tests that fail (I think) purely because the comparisons of the directories fails. I am not sure what the problem is as the tests don't tell you what is different, but it may be due to architecture differences.

**Pull request merged**
