### PR TITLE
Doc string finishing

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
I guess #24 when merged caused the conflict...

**Comment by GDYendell** [comment]
Fixed.

**Comment by ulrikpedersen** [comment]
I've added  a few fixes to docstrings with regards to formatting for sphinx. Mostly I've added type information to arguments and returns statements... I didn't get very far, please can you double-check the remainder of the functions, @GDYendell?

Also I get a sphinx warning that sounds like it should be fixed somewhere:

```
/scratch/aderepos/dls_ade/docs/dls_ade.rst:71: WARNING: autodoc: failed to import module u'dls_ade.get_new_module_creator'; the following exception was raised:
Traceback (most recent call last):
  File "/scratch/aderepos/dls_ade/venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named get_new_module_creator
docstring of dls_ade.new_module_creator.ModuleTemplateSupportAndIOC:8: ERROR: Unexpected indentation.
docstring of dls_ade.new_module_creator.ModuleTemplateTools:5: ERROR: Unexpected indentation.
/scratch/aderepos/dls_ade/docs/dls_ade.rst:81: WARNING: autodoc: failed to import module u'dls_ade.new_module_template'; the following exception was raised:
Traceback (most recent call last):
  File "/scratch/aderepos/dls_ade/venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named new_module_template
/scratch/aderepos/dls_ade/docs/dls_environment.rst:4: WARNING: autodoc: failed to import module u'dls_environment.dls_environment'; the following exception was raised:
Traceback (most recent call last):
  File "/scratch/aderepos/dls_ade/venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named dls_environment
```

**Comment by ulrikpedersen** [comment]
As just discussed @GDYendell: push your latest fixes and then do the merge, please.
Thanks!

**Pull request merged**
