### PR TITLE
Systemtests

### PR DESCRIPTION
**Pull request by skyfrench**
Fixes to the system tests for the dls-python (2.7) environment.
The tests now run, albeit with no improvements.

### CODE REVIEW

**Comment by GDYendell** [comment]
Does anyone know why it is now necessary to _require("GitPython")_ in setup-testing_environment and system_testing?

I checked out and tried this with aa26b16, which is just after I refactored to make Bitbucket and Gitolite easily swappable, and it works without the requires. I believe it also worked from that commit onward when I was running system tests against Bitbucket.

**Comment by skyfrench** [comment]
Committed a minor improvement. Modifications made to test error and output messages contain a list of items (or just one list item, if a single string is still specified) rather than testing against an entire string. Should reduce the need to update tests when punctuation, new line positioning and so on changes.

**Comment by MJGaughran** [comment]
There is more documentation in the 'docs' folder. It doesn't have an example shell, but combined with 'instructions.txt' it gives the full picture.

**Comment by skyfrench** [comment]
The instructions.txt has now been replaced with an updated README.md file (I have added a link within this to the documentation in 'docs'). I had to make a few (slight) modifications to the instructions to get the system tests to run for me; I have reflected these changes in the README.md file (and an update to setup_testing_environment.sh). The requirement to have permissions for the controlstest area has also been highlighted (I'm not sure how many people would have these permissions already).

**Comment by skyfrench** [comment]
> I ran into one other problem - on RHEL7 I get some tests that fail and they refer to EPICS version R3.14.12.7 instead of R3.14.12.3. I guess that some environment is being used somewhere, but I don't have time to follow it up.
When testing this branch with Python 3 on RHEL7 I do not encounter this issue ...
... I propose to revisit once this pull requested has been merged; then I can test with Python 3 re-based to a master which contains the systemtests changes.

**Comment by skyfrench** [comment]
Removing require('GitPython') (not needed).

**Pull request merged**
